name: UbuntuSSH
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 9999  # Add the timeout here
    steps: 
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - name: Session Setup
      uses: mxschmitt/action-tmate@v3  # tmate session starts after the script runs
