name: UbuntuSSH
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 9999  # Add the timeout here
    steps: 
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v3  # Checkout the repository to access the script
    - name: Install Python
      run: sudo apt-get install python3  # Ensure Python is installed
    - name: Run Python Script
      run: python3 loop.py  # Run your Python script
    - name: Session Setup
      uses: mxschmitt/action-tmate@v3  # tmate session starts after the script runs
